title: The Green Stack
description: Cultivating Developer Knowledge, One Guide at a Time
author: Phillip Green
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - CODE_OF_CONDUCT.md

nav:
  - Home: /
  - Blog: /posts
  - Contribute: /CONTRIBUTING

collections:
  posts:
    output: true
    permalink: /:collection/:title/
