name: Update README with Blog Posts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'philgreen-dev/PhilGreen-Dev'
          token: ${{ secrets.PAT }}
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://philgreen-dev.github.io/developer-guides/feed.xml"
          max_post_count: 5
          commit_message: "Updated README with latest blog posts"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
